### PR TITLE
New tool exiftool added

### PR DESCRIPTION
**Pull request by rishig2003**
Exiftool is an amazing tool for getting some juicy information related to images. Hope this helps.

### CODE REVIEW

**Comment by karanS08** [comment]
Thanks for Contributing , Do leave a star to the repo . Happy Hacking !!!!

**Comment by rishig2003** [comment]
This PR will be accepted by Hacktober people right?

**Comment by rishig2003** [comment]
*Hacktoberfest

**Comment by rishig2003** [comment]
Hi!
Can you please add the hacktoberfest-accepted label in my PR?

Thanks

**Comment by rishig2003** [comment]
My PR was on exiftool

**Pull request merged**
